#cmakedefine SDL2COMPAT_VENDOR_INFO "@SDL2COMPAT_VENDOR_INFO@"
#define SDL_REVISION_NUMBER 0

#ifdef SDL2COMPAT_VENDOR_INFO
#define SDL_REVISION "@SDL_REVISION@ (" SDL2COMPAT_VENDOR_INFO ")"
#else
#define SDL_REVISION "@SDL_REVISION@"
#endif
