/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2022 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/* don't #pragma once this file, it gets #included multiple times! */

#ifndef SDL3_SYM
#define SDL3_SYM(rc,fn,params,args,ret)
#endif

#ifndef SDL3_SYM_PASSTHROUGH
#define SDL3_SYM_PASSTHROUGH(rc,fn,params,args,ret) SDL3_SYM(rc,fn,params,args,ret)
#endif

#ifndef SDL3_SYM_VARARGS
#define SDL3_SYM_VARARGS(rc,fn,params) SDL3_SYM(rc,fn,params,unused,unused)
#endif

SDL3_SYM_VARARGS(int,SetError,(SDL_PRINTF_FORMAT_STRING const char *a, ...))
SDL3_SYM_VARARGS(void,Log,(SDL_PRINTF_FORMAT_STRING const char *a, ...))
SDL3_SYM_VARARGS(void,LogVerbose,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogDebug,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogInfo,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogWarn,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogError,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogCritical,(int a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(void,LogMessage,(int a, SDL_LogPriority b, SDL_PRINTF_FORMAT_STRING const char *c, ...))
SDL3_SYM_VARARGS(int,sscanf,(const char *a, SDL_SCANF_FORMAT_STRING const char *b, ...))
SDL3_SYM_VARARGS(int,snprintf,(SDL_OUT_Z_CAP(b) char *a, size_t b, SDL_PRINTF_FORMAT_STRING const char *c, ...))

#if defined(__WIN32__) || defined(__GDK__)
SDL3_SYM_PASSTHROUGH(SDL_Thread*,CreateThread,(SDL_ThreadFunction a, const char *b, void *c, pfnSDL_CurrentBeginThread d, pfnSDL_CurrentEndThread e),(a,b,c,d,e),return)
#else
SDL3_SYM_PASSTHROUGH(SDL_Thread*,CreateThread,(SDL_ThreadFunction a, const char *b, void *c),(a,b,c),return)
#endif

#if defined(__WIN32__) || defined(__GDK__)
SDL3_SYM_PASSTHROUGH(int,RegisterApp,(const char *a, Uint32 b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,UnregisterApp,(void),(),)
#endif

#if defined(__WIN32__) || defined(__WINGDK__)
SDL3_SYM_PASSTHROUGH(int,Direct3D9GetAdapterIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(IDirect3DDevice9*,RenderGetD3D9Device,(SDL_Renderer *a),(a),return)
#endif

#ifdef __IOS__
SDL3_SYM_PASSTHROUGH(int,iPhoneSetAnimationCallback,(SDL_Window *a, int b, void (SDLCALL *c)(void *), void *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(void,iPhoneSetEventPump,(SDL_bool a),(a),)
#endif

#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(void*,AndroidGetJNIEnv,(void),(),return)
SDL3_SYM_PASSTHROUGH(void*,AndroidGetActivity,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,AndroidGetInternalStoragePath,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,AndroidGetExternalStorageState,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,AndroidGetExternalStoragePath,(void),(),return)
#endif

SDL3_SYM_PASSTHROUGH(int,Init,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(int,InitSubSystem,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(void,QuitSubSystem,(Uint32 a),(a),)
SDL3_SYM_PASSTHROUGH(Uint32,WasInit,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(void,Quit,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_AssertState,ReportAssertion,(SDL_AssertData *a, const char *b, const char *c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(void,SetAssertionHandler,(SDL_AssertionHandler a, void *b),(a,b),)
SDL3_SYM_PASSTHROUGH(const SDL_AssertData*,GetAssertionReport,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,ResetAssertionReport,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,AtomicTryLock,(SDL_SpinLock *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,AtomicLock,(SDL_SpinLock *a),(a),)
SDL3_SYM_PASSTHROUGH(void,AtomicUnlock,(SDL_SpinLock *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_bool,AtomicCAS,(SDL_atomic_t *a, int b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,AtomicSet,(SDL_atomic_t *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,AtomicGet,(SDL_atomic_t *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,AtomicAdd,(SDL_atomic_t *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,AtomicCASPtr,(void **a, void *b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void*,AtomicSetPtr,(void **a, void *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void*,AtomicGetPtr,(void **a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetNumAudioDrivers,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,GetAudioDriver,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GetCurrentAudioDriver,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,OpenAudio,(SDL_AudioSpec *a, SDL_AudioSpec *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetNumAudioDevices,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GetAudioDeviceName,(int a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_AudioDeviceID,OpenAudioDevice,(const char *a, int b, const SDL_AudioSpec *c, SDL_AudioSpec *d, int e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(SDL_AudioStatus,GetAudioStatus,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_AudioStatus,GetAudioDeviceStatus,(SDL_AudioDeviceID a),(a),return)
SDL3_SYM_PASSTHROUGH(void,PauseAudio,(int a),(a),)
SDL3_SYM_PASSTHROUGH(void,PauseAudioDevice,(SDL_AudioDeviceID a, int b),(a,b),)
SDL3_SYM(SDL_AudioSpec*,LoadWAV_RW,(SDL_RWops *a, int b, SDL_AudioSpec *c, Uint8 **d, Uint32 *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,BuildAudioCVT,(SDL_AudioCVT *a, SDL_AudioFormat b, Uint8 c, int d, SDL_AudioFormat e, Uint8 f, int g),(a,b,c,d,e,f,g),return)
SDL3_SYM_PASSTHROUGH(int,ConvertAudio,(SDL_AudioCVT *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,MixAudio,(Uint8 *a, const Uint8 *b, Uint32 c, int d),(a,b,c,d),)
SDL3_SYM_PASSTHROUGH(void,MixAudioFormat,(Uint8 *a, const Uint8 *b, SDL_AudioFormat c, Uint32 d, int e),(a,b,c,d,e),)
SDL3_SYM_PASSTHROUGH(void,LockAudio,(void),(),)
SDL3_SYM_PASSTHROUGH(void,LockAudioDevice,(SDL_AudioDeviceID a),(a),)
SDL3_SYM_PASSTHROUGH(void,UnlockAudio,(void),(),)
SDL3_SYM_PASSTHROUGH(void,UnlockAudioDevice,(SDL_AudioDeviceID a),(a),)
SDL3_SYM_PASSTHROUGH(void,CloseAudio,(void),(),)
SDL3_SYM_PASSTHROUGH(void,CloseAudioDevice,(SDL_AudioDeviceID a),(a),)
SDL3_SYM_PASSTHROUGH(int,SetClipboardText,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GetClipboardText,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasClipboardText,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GetCPUCount,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GetCPUCacheLineSize,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasRDTSC,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasAltiVec,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasMMX,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSSE,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSSE2,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSSE3,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSSE41,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSSE42,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GetSystemRAM,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,GetError,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,ClearError,(void),(),)
SDL3_SYM_PASSTHROUGH(int,Error,(SDL_errorcode a),(a),return)
SDL3_SYM_PASSTHROUGH(void,PumpEvents,(void),(),)
SDL3_SYM(int,PeepEvents,(SDL_Event *a, int b, SDL_eventaction c, Uint32 d, Uint32 e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasEvent,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasEvents,(Uint32 a, Uint32 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,FlushEvent,(Uint32 a),(a),)
SDL3_SYM_PASSTHROUGH(void,FlushEvents,(Uint32 a, Uint32 b),(a,b),)
SDL3_SYM(int,PollEvent,(SDL_Event *a),(a),return)
SDL3_SYM(int,WaitEvent,(SDL_Event *a),(a),return)
SDL3_SYM(int,WaitEventTimeout,(SDL_Event *a, int b),(a,b),return)
SDL3_SYM(int,PushEvent,(SDL_Event *a),(a),return)
SDL3_SYM(void,SetEventFilter,(SDL_EventFilter a, void *b),(a,b),)
SDL3_SYM(SDL_bool,GetEventFilter,(SDL_EventFilter *a, void **b),(a,b),return)
SDL3_SYM(void,AddEventWatch,(SDL_EventFilter a, void *b),(a,b),)
SDL3_SYM(void,DelEventWatch,(SDL_EventFilter a, void *b),(a,b),)
SDL3_SYM(void,FilterEvents,(SDL_EventFilter a, void *b),(a,b),)
SDL3_SYM_PASSTHROUGH(Uint8,EventState,(Uint32 a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint32,RegisterEvents,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GetBasePath,(void),(),return)
SDL3_SYM_PASSTHROUGH(char*,GetPrefPath,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerAddMapping,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GameControllerMappingForGUID,(SDL_JoystickGUID a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GameControllerMapping,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsGameController,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerNameForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameController*,GameControllerOpen,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerName,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerGetAttached,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Joystick*,GameControllerGetJoystick,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerEventState,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void,GameControllerUpdate,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerAxis,GameControllerGetAxisFromString,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerGetStringForAxis,(SDL_GameControllerAxis a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerButtonBind,GameControllerGetBindForAxis,(SDL_GameController *a, SDL_GameControllerAxis b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Sint16,GameControllerGetAxis,(SDL_GameController *a, SDL_GameControllerAxis b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerButton,GameControllerGetButtonFromString,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerGetStringForButton,(SDL_GameControllerButton a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerButtonBind,GameControllerGetBindForButton,(SDL_GameController *a, SDL_GameControllerButton b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint8,GameControllerGetButton,(SDL_GameController *a, SDL_GameControllerButton b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,GameControllerClose,(SDL_GameController *a),(a),)
SDL3_SYM_PASSTHROUGH(int,NumHaptics,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,HapticName,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Haptic*,HapticOpen,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticOpened,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticIndex,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,MouseIsHaptic,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_Haptic*,HapticOpenFromMouse,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,JoystickIsHaptic,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Haptic*,HapticOpenFromJoystick,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,HapticClose,(SDL_Haptic *a),(a),)
SDL3_SYM_PASSTHROUGH(int,HapticNumEffects,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticNumEffectsPlaying,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(unsigned int,HapticQuery,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticNumAxes,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticEffectSupported,(SDL_Haptic *a, SDL_HapticEffect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,HapticNewEffect,(SDL_Haptic *a, SDL_HapticEffect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,HapticUpdateEffect,(SDL_Haptic *a, int b, SDL_HapticEffect *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,HapticRunEffect,(SDL_Haptic *a, int b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,HapticStopEffect,(SDL_Haptic *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,HapticDestroyEffect,(SDL_Haptic *a, int b),(a,b),)
SDL3_SYM_PASSTHROUGH(int,HapticGetEffectStatus,(SDL_Haptic *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,HapticSetGain,(SDL_Haptic *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,HapticSetAutocenter,(SDL_Haptic *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,HapticPause,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticUnpause,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticStopAll,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticRumbleSupported,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticRumbleInit,(SDL_Haptic *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,HapticRumblePlay,(SDL_Haptic *a, float b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,HapticRumbleStop,(SDL_Haptic *a),(a),return)
SDL3_SYM(SDL_bool,SetHintWithPriority,(const char *a, const char *b, SDL_HintPriority c),(a,b,c),return)
SDL3_SYM(SDL_bool,SetHint,(const char *a, const char *b),(a,b),return)
SDL3_SYM(const char*,GetHint,(const char *a),(a),return)
SDL3_SYM(void,AddHintCallback,(const char *a, SDL_HintCallback b, void *c),(a,b,c),)
SDL3_SYM(void,DelHintCallback,(const char *a, SDL_HintCallback b, void *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,ClearHints,(void),(),)
SDL3_SYM_PASSTHROUGH(int,NumJoysticks,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,JoystickNameForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Joystick*,JoystickOpen,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,JoystickName,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickGUID,JoystickGetDeviceGUID,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickGUID,JoystickGetGUID,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,JoystickGetGUIDString,(SDL_JoystickGUID a, char *b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(SDL_JoystickGUID,JoystickGetGUIDFromString,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickGetAttached,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickID,JoystickInstanceID,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickNumAxes,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickNumHats,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickNumButtons,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,JoystickUpdate,(void),(),)
SDL3_SYM_PASSTHROUGH(int,JoystickEventState,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(Sint16,JoystickGetAxis,(SDL_Joystick *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint8,JoystickGetHat,(SDL_Joystick *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint8,JoystickGetButton,(SDL_Joystick *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,JoystickClose,(SDL_Joystick *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_Window*,GetKeyboardFocus,(void),(),return)
SDL3_SYM_PASSTHROUGH(const Uint8*,GetKeyboardState,(int *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Keymod,GetModState,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,SetModState,(SDL_Keymod a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_Keycode,GetKeyFromScancode,(SDL_Scancode a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Scancode,GetScancodeFromKey,(SDL_Keycode a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GetScancodeName,(SDL_Scancode a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Scancode,GetScancodeFromName,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GetKeyName,(SDL_Keycode a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Keycode,GetKeyFromName,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,StartTextInput,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsTextInputActive,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,StopTextInput,(void),(),)
SDL3_SYM_PASSTHROUGH(void,SetTextInputRect,(const SDL_Rect *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasScreenKeyboardSupport,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsScreenKeyboardShown,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,LoadObject,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,LoadFunction,(void *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,UnloadObject,(void *a),(a),)
SDL3_SYM_PASSTHROUGH(void,LogSetAllPriority,(SDL_LogPriority a),(a),)
SDL3_SYM_PASSTHROUGH(void,LogSetPriority,(int a, SDL_LogPriority b),(a,b),)
SDL3_SYM_PASSTHROUGH(SDL_LogPriority,LogGetPriority,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void,LogResetPriorities,(void),(),)
SDL3_SYM_PASSTHROUGH(void,LogMessageV,(int a, SDL_LogPriority b, const char *c, va_list d),(a,b,c,d),)
SDL3_SYM_PASSTHROUGH(void,LogGetOutputFunction,(SDL_LogOutputFunction *a, void **b),(a,b),)
SDL3_SYM_PASSTHROUGH(void,LogSetOutputFunction,(SDL_LogOutputFunction a, void *b),(a,b),)
SDL3_SYM_PASSTHROUGH(void,SetMainReady,(void),(),)
SDL3_SYM_PASSTHROUGH(int,ShowMessageBox,(const SDL_MessageBoxData *a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,ShowSimpleMessageBox,(Uint32 a, const char *b, const char *c, SDL_Window *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,GetMouseFocus,(void),(),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetMouseState,(int *a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetRelativeMouseState,(int *a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,WarpMouseInWindow,(SDL_Window *a, int b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(int,SetRelativeMouseMode,(SDL_bool a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GetRelativeMouseMode,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_Cursor*,CreateCursor,(const Uint8 *a, const Uint8 *b, int c, int d, int e, int f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(SDL_Cursor*,CreateColorCursor,(SDL_Surface *a, int b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_Cursor*,CreateSystemCursor,(SDL_SystemCursor a),(a),return)
SDL3_SYM_PASSTHROUGH(void,SetCursor,(SDL_Cursor *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_Cursor*,GetCursor,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_Cursor*,GetDefaultCursor,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,FreeCursor,(SDL_Cursor *a),(a),)
SDL3_SYM_PASSTHROUGH(int,ShowCursor,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_mutex*,CreateMutex,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,LockMutex,(SDL_mutex *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,TryLockMutex,(SDL_mutex *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,UnlockMutex,(SDL_mutex *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,DestroyMutex,(SDL_mutex *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_sem*,CreateSemaphore,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(void,DestroySemaphore,(SDL_sem *a),(a),)
SDL3_SYM_PASSTHROUGH(int,SemWait,(SDL_sem *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SemTryWait,(SDL_sem *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SemWaitTimeout,(SDL_sem *a, Uint32 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SemPost,(SDL_sem *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint32,SemValue,(SDL_sem *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_cond*,CreateCond,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,DestroyCond,(SDL_cond *a),(a),)
SDL3_SYM_PASSTHROUGH(int,CondSignal,(SDL_cond *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,CondBroadcast,(SDL_cond *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,CondWait,(SDL_cond *a, SDL_mutex *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,CondWaitTimeout,(SDL_cond *a, SDL_mutex *b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(const char*,GetPixelFormatName,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,PixelFormatEnumToMasks,(Uint32 a, int *b, Uint32 *c, Uint32 *d, Uint32 *e, Uint32 *f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(Uint32,MasksToPixelFormatEnum,(int a, Uint32 b, Uint32 c, Uint32 d, Uint32 e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(SDL_PixelFormat*,AllocFormat,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(void,FreeFormat,(SDL_PixelFormat *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_Palette*,AllocPalette,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetPixelFormatPalette,(SDL_PixelFormat *a, SDL_Palette *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetPaletteColors,(SDL_Palette *a, const SDL_Color *b, int c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(void,FreePalette,(SDL_Palette *a),(a),)
SDL3_SYM_PASSTHROUGH(Uint32,MapRGB,(const SDL_PixelFormat *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(Uint32,MapRGBA,(const SDL_PixelFormat *a, Uint8 b, Uint8 c, Uint8 d, Uint8 e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(void,GetRGB,(Uint32 a, const SDL_PixelFormat *b, Uint8 *c, Uint8 *d, Uint8 *e),(a,b,c,d,e),)
SDL3_SYM_PASSTHROUGH(void,GetRGBA,(Uint32 a, const SDL_PixelFormat *b, Uint8 *c, Uint8 *d, Uint8 *e, Uint8 *f),(a,b,c,d,e,f),)
SDL3_SYM_PASSTHROUGH(const char*,GetPlatform,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_PowerState,GetPowerInfo,(int *a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasIntersection,(const SDL_Rect *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IntersectRect,(const SDL_Rect *a, const SDL_Rect *b, SDL_Rect *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,UnionRect,(const SDL_Rect *a, const SDL_Rect *b, SDL_Rect *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(SDL_bool,EnclosePoints,(const SDL_Point *a, int b, const SDL_Rect *c, SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IntersectRectAndLine,(const SDL_Rect *a, int *b, int *c, int *d, int *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,GetNumRenderDrivers,(void),(),return)
SDL3_SYM(const char *,GetRenderDriver,(int a),(a),return);
SDL3_SYM_PASSTHROUGH(int,CreateWindowAndRenderer,(int a, int b, Uint32 c, SDL_Window **d, SDL_Renderer **e),(a,b,c,d,e),return)
SDL3_SYM(SDL_Renderer*,CreateRenderer,(SDL_Window *a, const char *b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_Renderer*,CreateSoftwareRenderer,(SDL_Surface *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Renderer*,GetRenderer,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetRendererInfo,(SDL_Renderer *a, SDL_RendererInfo *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetRendererOutputSize,(SDL_Renderer *a, int *b, int *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_Texture*,CreateTexture,(SDL_Renderer *a, Uint32 b, int c, int d, int e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(SDL_Texture*,CreateTextureFromSurface,(SDL_Renderer *a, SDL_Surface *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,QueryTexture,(SDL_Texture *a, Uint32 *b, int *c, int *d, int *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,SetTextureColorMod,(SDL_Texture *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,GetTextureColorMod,(SDL_Texture *a, Uint8 *b, Uint8 *c, Uint8 *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,SetTextureAlphaMod,(SDL_Texture *a, Uint8 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetTextureAlphaMod,(SDL_Texture *a, Uint8 *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetTextureBlendMode,(SDL_Texture *a, SDL_BlendMode b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetTextureBlendMode,(SDL_Texture *a, SDL_BlendMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,UpdateTexture,(SDL_Texture *a, const SDL_Rect *b, const void *c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,UpdateYUVTexture,(SDL_Texture *a, const SDL_Rect *b, const Uint8 *c, int d, const Uint8 *e, int f, const Uint8 *g, int h),(a,b,c,d,e,f,g,h),return)
SDL3_SYM_PASSTHROUGH(int,LockTexture,(SDL_Texture *a, const SDL_Rect *b, void **c, int *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(void,UnlockTexture,(SDL_Texture *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_bool,RenderTargetSupported,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetRenderTarget,(SDL_Renderer *a, SDL_Texture *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_Texture*,GetRenderTarget,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,RenderSetLogicalSize,(SDL_Renderer *a, int b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,RenderGetLogicalSize,(SDL_Renderer *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(int,RenderSetViewport,(SDL_Renderer *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,RenderGetViewport,(SDL_Renderer *a, SDL_Rect *b),(a,b),)
SDL3_SYM_PASSTHROUGH(int,RenderSetClipRect,(SDL_Renderer *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,RenderGetClipRect,(SDL_Renderer *a, SDL_Rect *b),(a,b),)
SDL3_SYM_PASSTHROUGH(int,RenderSetScale,(SDL_Renderer *a, float b, float c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,RenderGetScale,(SDL_Renderer *a, float *b, float *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(int,SetRenderDrawColor,(SDL_Renderer *a, Uint8 b, Uint8 c, Uint8 d, Uint8 e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,GetRenderDrawColor,(SDL_Renderer *a, Uint8 *b, Uint8 *c, Uint8 *d, Uint8 *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,SetRenderDrawBlendMode,(SDL_Renderer *a, SDL_BlendMode b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetRenderDrawBlendMode,(SDL_Renderer *a, SDL_BlendMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderClear,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawPoint,(SDL_Renderer *a, int b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawPoints,(SDL_Renderer *a, const SDL_Point *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawLine,(SDL_Renderer *a, int b, int c, int d, int e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawLines,(SDL_Renderer *a, const SDL_Point *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawRect,(SDL_Renderer *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawRects,(SDL_Renderer *a, const SDL_Rect *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderFillRect,(SDL_Renderer *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderFillRects,(SDL_Renderer *a, const SDL_Rect *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderCopy,(SDL_Renderer *a, SDL_Texture *b, const SDL_Rect *c, const SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,RenderCopyEx,(SDL_Renderer *a, SDL_Texture *b, const SDL_Rect *c, const SDL_Rect *d, const double e, const SDL_Point *f, const SDL_RendererFlip g),(a,b,c,d,e,f,g),return)
SDL3_SYM_PASSTHROUGH(int,RenderReadPixels,(SDL_Renderer *a, const SDL_Rect *b, Uint32 c, void *d, int e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(void,RenderPresent,(SDL_Renderer *a),(a),)
SDL3_SYM_PASSTHROUGH(void,DestroyTexture,(SDL_Texture *a),(a),)
SDL3_SYM_PASSTHROUGH(void,DestroyRenderer,(SDL_Renderer *a),(a),)
SDL3_SYM_PASSTHROUGH(int,GL_BindTexture,(SDL_Texture *a, float *b, float *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GL_UnbindTexture,(SDL_Texture *a),(a),return)
SDL3_SYM(SDL_RWops*,RWFromFile,(const char *a, const char *b),(a,b),return)
SDL3_SYM(SDL_RWops*,RWFromMem,(void *a, int b),(a,b),return)
SDL3_SYM(SDL_RWops*,RWFromConstMem,(const void *a, int b),(a,b),return)
SDL3_SYM(SDL_RWops*,AllocRW,(void),(),return)
SDL3_SYM(void,FreeRW,(SDL_RWops *a),(a),)
SDL3_SYM(Uint8,ReadU8,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint16,ReadLE16,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint16,ReadBE16,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint32,ReadLE32,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint32,ReadBE32,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint64,ReadLE64,(SDL_RWops *a),(a),return)
SDL3_SYM(Uint64,ReadBE64,(SDL_RWops *a),(a),return)
SDL3_SYM(size_t,WriteU8,(SDL_RWops *a, Uint8 b),(a,b),return)
SDL3_SYM(size_t,WriteLE16,(SDL_RWops *a, Uint16 b),(a,b),return)
SDL3_SYM(size_t,WriteBE16,(SDL_RWops *a, Uint16 b),(a,b),return)
SDL3_SYM(size_t,WriteLE32,(SDL_RWops *a, Uint32 b),(a,b),return)
SDL3_SYM(size_t,WriteBE32,(SDL_RWops *a, Uint32 b),(a,b),return)
SDL3_SYM(size_t,WriteLE64,(SDL_RWops *a, Uint64 b),(a,b),return)
SDL3_SYM(size_t,WriteBE64,(SDL_RWops *a, Uint64 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,CreateShapedWindow,(const char *a, unsigned int b, unsigned int c, unsigned int d, unsigned int e, Uint32 f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsShapedWindow,(const SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowShape,(SDL_Window *a, SDL_Surface *b, SDL_WindowShapeMode *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GetShapedWindowMode,(SDL_Window *a, SDL_WindowShapeMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void*,malloc,(size_t a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,calloc,(size_t a, size_t b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void*,realloc,(void *a, size_t b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,free,(void *a),(a),)
SDL3_SYM_PASSTHROUGH(char*,getenv,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,setenv,(const char *a, const char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,qsort,(void *a, size_t b, size_t c, int (SDLCALL *d)(const void *, const void *)),(a,b,c,d),)
SDL3_SYM_PASSTHROUGH(int,abs,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isdigit,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isspace,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,toupper,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,tolower,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,memset,(SDL_OUT_BYTECAP(c) void *a, int b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void*,memcpy,(SDL_OUT_BYTECAP(c) void *a, SDL_IN_BYTECAP(c) const void *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void*,memmove,(SDL_OUT_BYTECAP(c) void *a, SDL_IN_BYTECAP(c) const void *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,memcmp,(const void *a, const void *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(size_t,wcslen,(const wchar_t *a),(a),return)
SDL3_SYM_PASSTHROUGH(size_t,wcslcpy,(SDL_OUT_Z_CAP(c) wchar_t *a, const wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(size_t,wcslcat,(SDL_INOUT_Z_CAP(c) wchar_t *a, const wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(size_t,strlen,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(size_t,strlcpy,(SDL_OUT_Z_CAP(c) char *a, const char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(size_t,utf8strlcpy,(SDL_OUT_Z_CAP(c) char *a, const char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(size_t,strlcat,(SDL_INOUT_Z_CAP(c) char *a, const char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,strdup,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,strrev,(char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,strupr,(char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,strlwr,(char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,strchr,(const char *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(char*,strrchr,(const char *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(char*,strstr,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(char*,itoa,(int a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,uitoa,(unsigned int a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,ltoa,(long a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,ultoa,(unsigned long a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,lltoa,(Sint64 a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,ulltoa,(Uint64 a, char *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,atoi,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(double,atof,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(long,strtol,(const char *a, char **b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(unsigned long,strtoul,(const char *a, char **b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(Sint64,strtoll,(const char *a, char **b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(Uint64,strtoull,(const char *a, char **b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(double,strtod,(const char *a, char **b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,strcmp,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,strncmp,(const char *a, const char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,strcasecmp,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,strncasecmp,(const char *a, const char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,vsnprintf,(SDL_OUT_Z_CAP(b) char *a, size_t b, const char *c, va_list d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(double,acos,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,asin,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,atan,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,atan2,(double a, double b),(a,b),return)
SDL3_SYM_PASSTHROUGH(double,ceil,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,copysign,(double a, double b),(a,b),return)
SDL3_SYM_PASSTHROUGH(double,cos,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,cosf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(double,fabs,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,floor,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,log,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(double,pow,(double a, double b),(a,b),return)
SDL3_SYM_PASSTHROUGH(double,scalbn,(double a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(double,sin,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,sinf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(double,sqrt,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_iconv_t,iconv_open,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,iconv_close,(SDL_iconv_t a),(a),return)
SDL3_SYM_PASSTHROUGH(size_t,iconv,(SDL_iconv_t a, const char **b, size_t *c, char **d, size_t *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(char*,iconv_string,(const char *a, const char *b, const char *c, size_t d),(a,b,c,d),return)
SDL3_SYM(SDL_Surface*,CreateSurface,(int a, int b, Uint32 c),(a,b,c),return)
SDL3_SYM(SDL_Surface*,CreateSurfaceFrom,(void *a, int b, int c, int d, Uint32 e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(void,FreeSurface,(SDL_Surface *a),(a),)
SDL3_SYM_PASSTHROUGH(int,SetSurfacePalette,(SDL_Surface *a, SDL_Palette *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,LockSurface,(SDL_Surface *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,UnlockSurface,(SDL_Surface *a),(a),)
SDL3_SYM(SDL_Surface*,LoadBMP_RW,(SDL_RWops *a, int b),(a,b),return)
SDL3_SYM(int,SaveBMP_RW,(SDL_Surface *a, SDL_RWops *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,SetSurfaceRLE,(SDL_Surface *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetColorKey,(SDL_Surface *a, int b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GetColorKey,(SDL_Surface *a, Uint32 *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetSurfaceColorMod,(SDL_Surface *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,GetSurfaceColorMod,(SDL_Surface *a, Uint8 *b, Uint8 *c, Uint8 *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,SetSurfaceAlphaMod,(SDL_Surface *a, Uint8 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetSurfaceAlphaMod,(SDL_Surface *a, Uint8 *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetSurfaceBlendMode,(SDL_Surface *a, SDL_BlendMode b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetSurfaceBlendMode,(SDL_Surface *a, SDL_BlendMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,SetClipRect,(SDL_Surface *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,GetClipRect,(SDL_Surface *a, SDL_Rect *b),(a,b),)
SDL3_SYM(SDL_Surface*,ConvertSurface,(SDL_Surface *a, const SDL_PixelFormat *b),(a,b),return)
SDL3_SYM(SDL_Surface*,ConvertSurfaceFormat,(SDL_Surface *a, Uint32 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,ConvertPixels,(int a, int b, Uint32 c, const void *d, int e, Uint32 f, void *g, int h),(a,b,c,d,e,f,g,h),return)
SDL3_SYM_PASSTHROUGH(int,FillRect,(SDL_Surface *a, const SDL_Rect *b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,FillRects,(SDL_Surface *a, const SDL_Rect *b, int c, Uint32 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,UpperBlit,(SDL_Surface *a, const SDL_Rect *b, SDL_Surface *c, SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,LowerBlit,(SDL_Surface *a, SDL_Rect *b, SDL_Surface *c, SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,SoftStretch,(SDL_Surface *a, const SDL_Rect *b, SDL_Surface *c, const SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,UpperBlitScaled,(SDL_Surface *a, const SDL_Rect *b, SDL_Surface *c, SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,LowerBlitScaled,(SDL_Surface *a, SDL_Rect *b, SDL_Surface *c, SDL_Rect *d),(a,b,c,d),return)
SDL3_SYM(SDL_bool,GetWindowWMInfo,(SDL_Window *a, SDL_SysWMinfo *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(const char*,GetThreadName,(SDL_Thread *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_threadID,ThreadID,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_threadID,GetThreadID,(SDL_Thread *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetThreadPriority,(SDL_ThreadPriority a),(a),return)
SDL3_SYM_PASSTHROUGH(void,WaitThread,(SDL_Thread *a, int *b),(a,b),)
SDL3_SYM_PASSTHROUGH(void,DetachThread,(SDL_Thread *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_TLSID,TLSCreate,(void),(),return)
SDL3_SYM_PASSTHROUGH(void*,TLSGet,(SDL_TLSID a),(a),return)
SDL3_SYM_PASSTHROUGH(int,TLSSet,(SDL_TLSID a, const void *b, void (SDLCALL *c)(void*)),(a,b,c),return)
SDL3_SYM(Uint64,GetTicks,(void),(),return)
SDL3_SYM_PASSTHROUGH(Uint64,GetPerformanceCounter,(void),(),return)
SDL3_SYM_PASSTHROUGH(Uint64,GetPerformanceFrequency,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,Delay,(Uint32 a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_TimerID,AddTimer,(Uint32 a, SDL_TimerCallback b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,RemoveTimer,(SDL_TimerID a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetNumTouchDevices,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_TouchID,GetTouchDevice,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetNumTouchFingers,(SDL_TouchID a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Finger*,GetTouchFinger,(SDL_TouchID a, int b),(a,b),return)
SDL3_SYM(void,GetVersion,(SDL_version *a),(a),)
SDL3_SYM_PASSTHROUGH(const char*,GetRevision,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GetNumVideoDrivers,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,GetVideoDriver,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GetCurrentVideoDriver,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GetNumVideoDisplays,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,GetDisplayName,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetDisplayBounds,(int a, SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetNumDisplayModes,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetDisplayMode,(int a, int b, SDL_DisplayMode *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GetDesktopDisplayMode,(int a, SDL_DisplayMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetCurrentDisplayMode,(int a, SDL_DisplayMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_DisplayMode*,GetClosestDisplayMode,(int a, const SDL_DisplayMode *b, SDL_DisplayMode *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GetWindowDisplayIndex,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowDisplayMode,(SDL_Window *a, const SDL_DisplayMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetWindowDisplayMode,(SDL_Window *a, SDL_DisplayMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetWindowPixelFormat,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,CreateWindow,(const char *a, int b, int c, int d, int e, Uint32 f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,CreateWindowFrom,(const void *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetWindowID,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,GetWindowFromID,(Uint32 a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetWindowFlags,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowTitle,(SDL_Window *a, const char *b),(a,b),)
SDL3_SYM_PASSTHROUGH(const char*,GetWindowTitle,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowIcon,(SDL_Window *a, SDL_Surface *b),(a,b),)
SDL3_SYM_PASSTHROUGH(void*,SetWindowData,(SDL_Window *a, const char *b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void*,GetWindowData,(SDL_Window *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowPosition,(SDL_Window *a, int b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,GetWindowPosition,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,SetWindowSize,(SDL_Window *a, int b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,GetWindowSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,SetWindowMinimumSize,(SDL_Window *a, int b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,GetWindowMinimumSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,SetWindowMaximumSize,(SDL_Window *a, int b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,GetWindowMaximumSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,SetWindowBordered,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM_PASSTHROUGH(void,ShowWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,HideWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,RaiseWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,MaximizeWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,MinimizeWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,RestoreWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(int,SetWindowFullscreen,(SDL_Window *a, Uint32 b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_Surface*,GetWindowSurface,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,UpdateWindowSurface,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,UpdateWindowSurfaceRects,(SDL_Window *a, const SDL_Rect *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowGrab,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM_PASSTHROUGH(SDL_bool,GetWindowGrab,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,DestroyWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsScreenSaverEnabled,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,EnableScreenSaver,(void),(),)
SDL3_SYM_PASSTHROUGH(void,DisableScreenSaver,(void),(),)
SDL3_SYM_PASSTHROUGH(int,GL_LoadLibrary,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,GL_GetProcAddress,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,GL_UnloadLibrary,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,GL_ExtensionSupported,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GL_SetAttribute,(SDL_GLattr a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GL_GetAttribute,(SDL_GLattr a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_GLContext,GL_CreateContext,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GL_MakeCurrent,(SDL_Window *a, SDL_GLContext b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,GL_GetCurrentWindow,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_GLContext,GL_GetCurrentContext,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,GL_GetDrawableSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(int,GL_SetSwapInterval,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GL_GetSwapInterval,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,GL_SwapWindow,(SDL_Window *a),(a),)
SDL3_SYM_PASSTHROUGH(void,GL_DeleteContext,(SDL_GLContext a),(a),)
SDL3_SYM_PASSTHROUGH(int,vsscanf,(const char *a, const char *b, va_list c),(a,b,c),return)
SDL3_SYM(int,GameControllerAddMappingsFromRW,(SDL_RWops *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,GL_ResetAttributes,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasAVX,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_AssertionHandler,GetDefaultAssertionHandler,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_AssertionHandler,GetAssertionHandler,(void **a),(a),return)
#if defined(__WIN32__) || defined(__WINGDK__)
SDL3_SYM_PASSTHROUGH(SDL_bool,DXGIGetOutputInfo,(int a,int *b, int *c),(a,b,c),return)
#endif
SDL3_SYM_PASSTHROUGH(SDL_bool,RenderIsClipEnabled,(SDL_Renderer *a),(a),return)
#ifdef __WINRT__
SDL3_SYM_PASSTHROUGH(int,WinRTRunApp,(int a, char **b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(const wchar_t*,WinRTGetFSPathUNICODE,(SDL_WinRT_Path a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,WinRTGetFSPathUTF8,(SDL_WinRT_Path a),(a),return)
#endif
SDL3_SYM_PASSTHROUGH(int,WarpMouseGlobal,(int a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(float,sqrtf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(double,tan,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,tanf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(int,CaptureMouse,(SDL_bool a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowHitTest,(SDL_Window *a, SDL_HitTest b, void *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetGlobalMouseState,(int *a, int *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasAVX2,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,QueueAudio,(SDL_AudioDeviceID a, const void *b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(Uint32,GetQueuedAudioSize,(SDL_AudioDeviceID a),(a),return)
SDL3_SYM_PASSTHROUGH(void,ClearQueuedAudio,(SDL_AudioDeviceID a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_Window*,GetGrabbedWindow,(void),(),return)
#if defined(__WIN32__) || defined(__GDK__)
SDL3_SYM_PASSTHROUGH(void,SetWindowsMessageHook,(SDL_WindowsMessageHook a, void *b),(a,b),)
#endif
SDL3_SYM_PASSTHROUGH(int,GetDisplayDPI,(int a, float *b, float *c, float *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickPowerLevel,JoystickCurrentPowerLevel,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameController*,GameControllerFromInstanceID,(SDL_JoystickID a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Joystick*,JoystickFromInstanceID,(SDL_JoystickID a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetDisplayUsableBounds,(int a, SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetWindowBordersSize,(SDL_Window *a, int *b, int *c, int *d, int *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowOpacity,(SDL_Window *a, float b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetWindowOpacity,(SDL_Window *a, float *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowInputFocus,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowModalFor,(SDL_Window *a, SDL_Window *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderSetIntegerScale,(SDL_Renderer *a, SDL_bool b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,RenderGetIntegerScale,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint32,DequeueAudio,(SDL_AudioDeviceID a, void *b, Uint32 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowResizable,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM(SDL_bool,GetHintBoolean,(const char *a, SDL_bool b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetDeviceVendor,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetDeviceProduct,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetDeviceProductVersion,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetVendor,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetProduct,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetProductVersion,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,GameControllerGetVendor,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,GameControllerGetProduct,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,GameControllerGetProductVersion,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasNEON,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerNumMappings,(void),(),return)
SDL3_SYM_PASSTHROUGH(char*,GameControllerMappingForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickGetAxisInitialState,(SDL_Joystick *a, int b, Sint16 *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickType,JoystickGetDeviceType,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_JoystickType,JoystickGetType,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,MemoryBarrierReleaseFunction,(void),(),)
SDL3_SYM_PASSTHROUGH(void,MemoryBarrierAcquireFunction,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_JoystickID,JoystickGetDeviceInstanceID,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(size_t,utf8strlen,(const char *a),(a),return)
SDL3_SYM(void*,LoadFile_RW,(SDL_RWops *a, size_t *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,wcscmp,(const wchar_t *a, const wchar_t *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_BlendMode,ComposeCustomBlendMode,(SDL_BlendFactor a, SDL_BlendFactor b, SDL_BlendOperation c, SDL_BlendFactor d, SDL_BlendFactor e, SDL_BlendOperation f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(SDL_Surface*,DuplicateSurface,(SDL_Surface *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,Vulkan_LoadLibrary,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,Vulkan_GetVkGetInstanceProcAddr,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,Vulkan_UnloadLibrary,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,Vulkan_GetInstanceExtensions,(SDL_Window *a, unsigned int *b, const char **c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,Vulkan_CreateSurface,(SDL_Window *a, VkInstance b, VkSurfaceKHR *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,Vulkan_GetDrawableSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,LockJoysticks,(void),(),)
SDL3_SYM_PASSTHROUGH(void,UnlockJoysticks,(void),(),)
SDL3_SYM_PASSTHROUGH(void,GetMemoryFunctions,(SDL_malloc_func *a, SDL_calloc_func *b, SDL_realloc_func *c, SDL_free_func *d),(a,b,c,d),)
SDL3_SYM_PASSTHROUGH(int,SetMemoryFunctions,(SDL_malloc_func a, SDL_calloc_func b, SDL_realloc_func c, SDL_free_func d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,GetNumAllocations,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_AudioStream*,NewAudioStream,(const SDL_AudioFormat a, const Uint8 b, const int c, const SDL_AudioFormat d, const Uint8 e, const int f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(int,AudioStreamPut,(SDL_AudioStream *a, const void *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,AudioStreamGet,(SDL_AudioStream *a, void *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,AudioStreamClear,(SDL_AudioStream *a),(a),)
SDL3_SYM_PASSTHROUGH(int,AudioStreamAvailable,(SDL_AudioStream *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,FreeAudioStream,(SDL_AudioStream *a),(a),)
SDL3_SYM_PASSTHROUGH(int,AudioStreamFlush,(SDL_AudioStream *a),(a),return)
SDL3_SYM_PASSTHROUGH(float,acosf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,asinf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,atanf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,atan2f,(float a, float b),(a,b),return)
SDL3_SYM_PASSTHROUGH(float,ceilf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,copysignf,(float a, float b),(a,b),return)
SDL3_SYM_PASSTHROUGH(float,fabsf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,floorf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,logf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(float,powf,(float a, float b),(a,b),return)
SDL3_SYM_PASSTHROUGH(float,scalbnf,(float a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(double,fmod,(double a, double b),(a,b),return)
SDL3_SYM_PASSTHROUGH(float,fmodf,(float a, float b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,SetYUVConversionMode,(SDL_YUV_CONVERSION_MODE a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_YUV_CONVERSION_MODE,GetYUVConversionMode,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_YUV_CONVERSION_MODE,GetYUVConversionModeForResolution,(int a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void*,RenderGetMetalLayer,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,RenderGetMetalCommandEncoder,(SDL_Renderer *a),(a),return)
#ifdef __WINRT__
SDL3_SYM_PASSTHROUGH(SDL_WinRT_DeviceFamily,WinRTGetDeviceFamily,(void),(),return)
#endif
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(SDL_bool,IsAndroidTV,(void),(),return)
#endif
SDL3_SYM_PASSTHROUGH(double,log10,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,log10f,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GameControllerMappingForDeviceIndex,(int a),(a),return)
#ifdef __LINUX__
SDL3_SYM_PASSTHROUGH(int,LinuxSetThreadPriority,(Sint64 a, int b),(a,b),return)
#endif
SDL3_SYM_PASSTHROUGH(SDL_bool,HasAVX512F,(void),(),return)
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(SDL_bool,IsChromebook,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsDeXMode,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,AndroidBackButton,(void),(),)
#endif
SDL3_SYM_PASSTHROUGH(double,exp,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,expf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(wchar_t*,wcsdup,(const wchar_t *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerRumble,(SDL_GameController *a, Uint16 b, Uint16 c, Uint32 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,JoystickRumble,(SDL_Joystick *a, Uint16 b, Uint16 c, Uint32 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,NumSensors,(void),(),return)
SDL3_SYM_PASSTHROUGH(const char*,SensorGetDeviceName,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_SensorType,SensorGetDeviceType,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SensorGetDeviceNonPortableType,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_SensorID,SensorGetDeviceInstanceID,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Sensor*,SensorOpen,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Sensor*,SensorFromInstanceID,(SDL_SensorID a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,SensorGetName,(SDL_Sensor *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_SensorType,SensorGetType,(SDL_Sensor *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SensorGetNonPortableType,(SDL_Sensor *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_SensorID,SensorGetInstanceID,(SDL_Sensor *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SensorGetData,(SDL_Sensor *a, float *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,SensorClose,(SDL_Sensor *a),(a),)
SDL3_SYM_PASSTHROUGH(void,SensorUpdate,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsTablet,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_DisplayOrientation,GetDisplayOrientation,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasColorKey,(SDL_Surface *a),(a),return)

#if defined(__WIN32__) || defined(__GDK__)
SDL3_SYM_PASSTHROUGH(SDL_Thread*,CreateThreadWithStackSize,(SDL_ThreadFunction a, const char *b, const size_t c, void *d, pfnSDL_CurrentBeginThread e, pfnSDL_CurrentEndThread f),(a,b,c,d,e,f),return)
#else
SDL3_SYM_PASSTHROUGH(SDL_Thread*,CreateThreadWithStackSize,(SDL_ThreadFunction a, const char *b, const size_t c, void *d),(a,b,c,d),return)
#endif

SDL3_SYM_PASSTHROUGH(int,JoystickGetDevicePlayerIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickGetPlayerIndex,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerGetPlayerIndex,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,RenderFlush,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawPointF,(SDL_Renderer *a, float b, float c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawPointsF,(SDL_Renderer *a, const SDL_FPoint *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawLineF,(SDL_Renderer *a, float b, float c, float d, float e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawLinesF,(SDL_Renderer *a, const SDL_FPoint *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawRectF,(SDL_Renderer *a, const SDL_FRect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderDrawRectsF,(SDL_Renderer *a, const SDL_FRect *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderFillRectF,(SDL_Renderer *a, const SDL_FRect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,RenderFillRectsF,(SDL_Renderer *a, const SDL_FRect *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,RenderCopyF,(SDL_Renderer *a, SDL_Texture *b, const SDL_Rect *c, const SDL_FRect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,RenderCopyExF,(SDL_Renderer *a, SDL_Texture *b, const SDL_Rect *c, const SDL_FRect *d, const double e, const SDL_FPoint *f, const SDL_RendererFlip g),(a,b,c,d,e,f,g),return)
SDL3_SYM_PASSTHROUGH(SDL_TouchDeviceType,GetTouchDeviceType,(SDL_TouchID a),(a),return)
#ifdef __IOS__
SDL3_SYM_PASSTHROUGH(int,UIKitRunApp,(int a, char *b, SDL_main_func c),(a,b,c),return)
#endif
SDL3_SYM_PASSTHROUGH(size_t,SIMDGetAlignment,(void),(),return)
SDL3_SYM_PASSTHROUGH(void*,SIMDAlloc,(const size_t a),(a),return)
SDL3_SYM_PASSTHROUGH(void,SIMDFree,(void *a),(a),)
SDL3_SYM(Sint64,RWsize,(SDL_RWops *a),(a),return)
SDL3_SYM(Sint64,RWseek,(SDL_RWops *a, Sint64 b, int c),(a,b,c),return)
SDL3_SYM(Sint64,RWtell,(SDL_RWops *a),(a),return)
SDL3_SYM(Sint64,RWread,(SDL_RWops *a, void *b, Sint64 c),(a,b,c),return)
SDL3_SYM(Sint64,RWwrite,(SDL_RWops *a, const void *b, Sint64 c),(a,b,c),return)
SDL3_SYM(int,RWclose,(SDL_RWops *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,LoadFile,(const char *a, size_t *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_MetalView,Metal_CreateView,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,Metal_DestroyView,(SDL_MetalView a),(a),)
SDL3_SYM_PASSTHROUGH(int,LockTextureToSurface,(SDL_Texture *a, const SDL_Rect *b, SDL_Surface **c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasARMSIMD,(void),(),return)
SDL3_SYM_PASSTHROUGH(char*,strtokr,(char *a, const char *b, char **c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(wchar_t*,wcsstr,(const wchar_t *a, const wchar_t *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,wcsncmp,(const wchar_t *a, const wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerType,GameControllerTypeForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameControllerType,GameControllerGetType,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_GameController*,GameControllerFromPlayerIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void,GameControllerSetPlayerIndex,(SDL_GameController *a, int b),(a,b),)
SDL3_SYM_PASSTHROUGH(SDL_Joystick*,JoystickFromPlayerIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void,JoystickSetPlayerIndex,(SDL_Joystick *a, int b),(a,b),)
SDL3_SYM_PASSTHROUGH(int,SetTextureScaleMode,(SDL_Texture *a, SDL_ScaleMode b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GetTextureScaleMode,(SDL_Texture *a, SDL_ScaleMode *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,OnApplicationWillTerminate,(void),(),)
SDL3_SYM_PASSTHROUGH(void,OnApplicationDidReceiveMemoryWarning,(void),(),)
SDL3_SYM_PASSTHROUGH(void,OnApplicationWillResignActive,(void),(),)
SDL3_SYM_PASSTHROUGH(void,OnApplicationDidEnterBackground,(void),(),)
SDL3_SYM_PASSTHROUGH(void,OnApplicationWillEnterForeground,(void),(),)
SDL3_SYM_PASSTHROUGH(void,OnApplicationDidBecomeActive,(void),(),)
#ifdef __IOS__
SDL3_SYM_PASSTHROUGH(void,OnApplicationDidChangeStatusBarOrientation,(void),(),)
#endif
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(int,GetAndroidSDKVersion,(void),(),return)
#endif
SDL3_SYM_PASSTHROUGH(int,isupper,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,islower,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickAttachVirtual,(SDL_JoystickType a, int b, int c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,JoystickDetachVirtual,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickIsVirtual,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickSetVirtualAxis,(SDL_Joystick *a, int b, Sint16 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,JoystickSetVirtualButton,(SDL_Joystick *a, int b, Uint8 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,JoystickSetVirtualHat,(SDL_Joystick *a, int b, Uint8 c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(char*,GetErrorMsg,(char *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,LockSensors,(void),(),)
SDL3_SYM_PASSTHROUGH(void,UnlockSensors,(void),(),)
SDL3_SYM_PASSTHROUGH(void*,Metal_GetLayer,(SDL_MetalView a),(a),return)
SDL3_SYM_PASSTHROUGH(void,Metal_GetDrawableSize,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(double,trunc,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,truncf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_Locale *,GetPreferredLocales,(void),(),return)
SDL3_SYM_PASSTHROUGH(void*,SIMDRealloc,(void *a, const size_t b),(a, b),return)
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(SDL_bool,AndroidRequestPermission,(const char *a),(a),return)
#endif
SDL3_SYM_PASSTHROUGH(int,OpenURL,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasSurfaceRLE,(SDL_Surface *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasLED,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerSetLED,(SDL_GameController *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickHasLED,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickSetLED,(SDL_Joystick *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerRumbleTriggers,(SDL_GameController *a, Uint16 b, Uint16 c, Uint32 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,JoystickRumbleTriggers,(SDL_Joystick *a, Uint16 b, Uint16 c, Uint32 d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasAxis,(SDL_GameController *a, SDL_GameControllerAxis b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasButton,(SDL_GameController *a, SDL_GameControllerButton b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerGetNumTouchpads,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerGetNumTouchpadFingers,(SDL_GameController *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerGetTouchpadFinger,(SDL_GameController *a, int b, int c, Uint8 *d, float *e, float *f, float *g),(a,b,c,d,e,f,g),return)
SDL3_SYM_PASSTHROUGH(Uint32,crc32,(Uint32 a, const void *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerGetSerial,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,JoystickGetSerial,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasSensor,(SDL_GameController *a, SDL_SensorType b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerSetSensorEnabled,(SDL_GameController *a, SDL_SensorType b, SDL_bool c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerIsSensorEnabled,(SDL_GameController *a, SDL_SensorType b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerGetSensorData,(SDL_GameController *a, SDL_SensorType b, float *c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,wcscasecmp,(const wchar_t *a, const wchar_t *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,wcsncasecmp,(const wchar_t *a, const wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(double,round,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(float,roundf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(long,lround,(double a),(a),return)
SDL3_SYM_PASSTHROUGH(long,lroundf,(float a),(a),return)
SDL3_SYM_PASSTHROUGH(int,SoftStretchLinear,(SDL_Surface *a, const SDL_Rect *b, SDL_Surface *c, const SDL_Rect *d),(a,b,c,d),return)
#if defined(__WIN32__) || defined(__WINGDK__)
SDL3_SYM_PASSTHROUGH(ID3D11Device*,RenderGetD3D11Device,(SDL_Renderer *a),(a),return)
#endif
SDL3_SYM_PASSTHROUGH(int,UpdateNVTexture,(SDL_Texture *a, const SDL_Rect *b, const Uint8 *c, int d, const Uint8 *e, int f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(void,SetWindowKeyboardGrab,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM_PASSTHROUGH(void,SetWindowMouseGrab,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM_PASSTHROUGH(SDL_bool,GetWindowKeyboardGrab,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GetWindowMouseGrab,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isalpha,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isalnum,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isblank,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,iscntrl,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isxdigit,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,ispunct,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isprint,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(int,isgraph,(int a),(a),return)
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(int,AndroidShowToast,(const char *a, int b, int c, int d, int e),(a,b,c,d,e),return)
#endif
SDL3_SYM_PASSTHROUGH(int,GetAudioDeviceSpec,(int a, int b, SDL_AudioSpec *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,TLSCleanup,(void),(),)
SDL3_SYM_PASSTHROUGH(void,SetWindowAlwaysOnTop,(SDL_Window *a, SDL_bool b),(a,b),)
SDL3_SYM_PASSTHROUGH(int,FlashWindow,(SDL_Window *a, SDL_FlashOperation b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,GameControllerSendEffect,(SDL_GameController *a, const void *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,JoystickSendEffect,(SDL_Joystick *a, const void *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(float,GameControllerGetSensorDataRate,(SDL_GameController *a, SDL_SensorType b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,SetTextureUserData,(SDL_Texture *a, void *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void*,GetTextureUserData,(SDL_Texture *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,RenderGeometry,(SDL_Renderer *a, SDL_Texture *b, const SDL_Vertex *c, int d, const int *e, int f),(a,b,c,d,e,f),return)
SDL3_SYM_PASSTHROUGH(int,RenderGeometryRaw,(SDL_Renderer *a, SDL_Texture *b, const float *c, int d, const SDL_Color *e, int f, const float *g, int h, int i, const void *j, int k, int l),(a,b,c,d,e,f,g,h,i,j,k,l),return)
SDL3_SYM_PASSTHROUGH(int,RenderSetVSync,(SDL_Renderer *a, int b),(a,b),return)
SDL3_SYM_VARARGS(int,asprintf,(char **a, SDL_PRINTF_FORMAT_STRING const char *b, ...))
SDL3_SYM_PASSTHROUGH(int,vasprintf,(char **a, const char *b, va_list c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void*,GetWindowICCProfile,(SDL_Window *a, size_t *b),(a,b),return)
#ifdef __LINUX__
SDL3_SYM_PASSTHROUGH(int,LinuxSetThreadPriorityAndPolicy,(Sint64 a, int b, int c),(a,b,c),return)
#endif
SDL3_SYM_PASSTHROUGH(const char*,GameControllerGetAppleSFSymbolsNameForButton,(SDL_GameController *a, SDL_GameControllerButton b),(a,b),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerGetAppleSFSymbolsNameForAxis,(SDL_GameController *a, SDL_GameControllerAxis b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,hid_init,(void),(),return)
SDL3_SYM_PASSTHROUGH(int,hid_exit,(void),(),return)
SDL3_SYM_PASSTHROUGH(Uint32,hid_device_change_count,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_hid_device_info*,hid_enumerate,(unsigned short a, unsigned short b),(a,b),return)
SDL3_SYM_PASSTHROUGH(void,hid_free_enumeration,(SDL_hid_device_info *a),(a),)
SDL3_SYM_PASSTHROUGH(SDL_hid_device*,hid_open,(unsigned short a, unsigned short b, const wchar_t *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(SDL_hid_device*,hid_open_path,(const char *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,hid_write,(SDL_hid_device *a, const unsigned char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_read_timeout,(SDL_hid_device *a, unsigned char *b, size_t c, int d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,hid_read,(SDL_hid_device *a, unsigned char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_set_nonblocking,(SDL_hid_device *a, int b),(a,b),return)
SDL3_SYM_PASSTHROUGH(int,hid_send_feature_report,(SDL_hid_device *a, const unsigned char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_get_feature_report,(SDL_hid_device *a, unsigned char *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,hid_close,(SDL_hid_device *a),(a),)
SDL3_SYM_PASSTHROUGH(int,hid_get_manufacturer_string,(SDL_hid_device *a, wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_get_product_string,(SDL_hid_device *a, wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_get_serial_number_string,(SDL_hid_device *a, wchar_t *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,hid_get_indexed_string,(SDL_hid_device *a, int b, wchar_t *c, size_t d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(int,SetWindowMouseRect,(SDL_Window *a, const SDL_Rect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(const SDL_Rect*,GetWindowMouseRect,(SDL_Window *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,RenderWindowToLogical,(SDL_Renderer *a, int b, int c, float *d, float *e),(a,b,c,d,e),)
SDL3_SYM_PASSTHROUGH(void,RenderLogicalToWindow,(SDL_Renderer *a, float b, float c, int *d, int *e),(a,b,c,d,e),)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickHasRumble,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,JoystickHasRumbleTriggers,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasRumble,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,GameControllerHasRumbleTriggers,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,hid_ble_scan,(SDL_bool a),(a),)
SDL3_SYM_PASSTHROUGH(int,PremultiplyAlpha,(int a, int b, Uint32 c, const void *d, int e, Uint32 f, void *g, int h),(a,b,c,d,e,f,g,h),return)
#ifdef __ANDROID__
SDL3_SYM_PASSTHROUGH(int,AndroidSendMessage,(Uint32 a, int b),(a,b),return)
#endif
SDL3_SYM_PASSTHROUGH(const char*,GetTouchName,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(void,ClearComposition,(void),(),)
SDL3_SYM_PASSTHROUGH(SDL_bool,IsTextInputShown,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasIntersectionF,(const SDL_FRect *a, const SDL_FRect *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IntersectFRect,(const SDL_FRect *a, const SDL_FRect *b, SDL_FRect *c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,UnionFRect,(const SDL_FRect *a, const SDL_FRect *b, SDL_FRect *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(SDL_bool,EncloseFPoints,(const SDL_FPoint *a, int b, const SDL_FRect *c, SDL_FRect *d),(a,b,c,d),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,IntersectFRectAndLine,(const SDL_FRect *a, float *b, float *c, float *d, float *e),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(SDL_Window*,RenderGetWindow,(SDL_Renderer *a),(a),return)
SDL3_SYM_PASSTHROUGH(void*,bsearch,(const void *a, const void *b, size_t c, size_t d, int (SDLCALL *e)(const void *, const void *)),(a,b,c,d,e),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerPathForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,GameControllerPath,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,JoystickPathForIndex,(int a),(a),return)
SDL3_SYM_PASSTHROUGH(const char*,JoystickPath,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,JoystickAttachVirtualEx,(const SDL_VirtualJoystickDesc *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,GameControllerGetFirmwareVersion,(SDL_GameController *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,JoystickGetFirmwareVersion,(SDL_Joystick *a),(a),return)
SDL3_SYM_PASSTHROUGH(void,GUIDToString,(SDL_GUID a, char *b, int c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(SDL_GUID,GUIDFromString,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasLSX,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasLASX,(void),(),return)
#if defined(__WIN32__) || defined(__GDK__)
SDL3_SYM_PASSTHROUGH(ID3D12Device*,RenderGetD3D12Device,(SDL_Renderer *a),(a),return)
#endif
SDL3_SYM_PASSTHROUGH(size_t,utf8strnlen,(const char *a, size_t b),(a,b),return)

#if defined(__GDK__)
SDL3_SYM_PASSTHROUGH(int,GDKGetTaskQueue,(XTaskQueueHandle *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GDKRunApp,(SDL_main_func a, void *b),(a,b),return)
#endif
SDL3_SYM_PASSTHROUGH(void,GetOriginalMemoryFunctions,(SDL_malloc_func *a, SDL_calloc_func *b, SDL_realloc_func *c, SDL_free_func *d),(a,b,c,d),)
SDL3_SYM_PASSTHROUGH(void,ResetKeyboard,(void),(),)
SDL3_SYM_PASSTHROUGH(int,GetDefaultAudioInfo,(char **a, SDL_AudioSpec *b, int c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(int,GetPointDisplayIndex,(const SDL_Point *a),(a),return)
SDL3_SYM_PASSTHROUGH(int,GetRectDisplayIndex,(const SDL_Rect *a),(a),return)
SDL3_SYM(SDL_bool,ResetHint,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(Uint16,crc16,(Uint16 a, const void *b, size_t c),(a,b,c),return)
SDL3_SYM_PASSTHROUGH(void,GetWindowSizeInPixels,(SDL_Window *a, int *b, int *c),(a,b,c),)
SDL3_SYM_PASSTHROUGH(void,GetJoystickGUIDInfo,(SDL_JoystickGUID a, Uint16 *b, Uint16 *c, Uint16 *d, Uint16 *e),(a,b,c,d,e),)
SDL3_SYM_PASSTHROUGH(int,SetPrimarySelectionText,(const char *a),(a),return)
SDL3_SYM_PASSTHROUGH(char*,GetPrimarySelectionText,(void),(),return)
SDL3_SYM_PASSTHROUGH(SDL_bool,HasPrimarySelectionText,(void),(),return)
SDL3_SYM_PASSTHROUGH(void,ResetHints,(void),(),)
SDL3_SYM_PASSTHROUGH(char*,strcasestr,(const char *a, const char *b),(a,b),return)
SDL3_SYM_PASSTHROUGH(Uint8,GetEventState,(Uint32 a),(a),return)

#undef SDL3_SYM
#undef SDL3_SYM_PASSTHROUGH
#undef SDL3_SYM_VARARGS

/* vi: set ts=4 sw=4 expandtab: */
